name: Deploy to Bastion EC2

on:
  push:
    branches:
      - main
    paths:
      - "ansible/**"

permissions:
  id-token: write
  contents: read

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  deploy_files:
    name: Deploy Files to Bastion EC2
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Zip files for transfer
        run: zip -r ansible.zip ansible/

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Copy files to Bastion EC2
        run: |
          scp -o StrictHostKeyChecking=no ansible.zip ubuntu@${{ vars.BASTION_HOST }}:~/

      - name: SSH into Bastion EC2 and Unzip Files
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.BASTION_HOST }}
          username: ubuntu
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          port: 22
          script: |
            unzip -o ~/ansible.zip -d ~/ansible/
            rm ~/ansible.zip

  setup_ec2:
    name: Setup EC2 Instances
    runs-on: ubuntu-latest
    needs: deploy_files
    steps:
      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: SSH into Bastion EC2 and Install Dependencies
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ vars.BASTION_HOST }}
          username: ubuntu
          key: ${{ secrets.BASTION_PRIVATE_KEY }}
          port: 22
          script: |
            sudo yum update -y
            sudo yum install -y python3
            sudo alternatives --set python /usr/bin/python3
            sudo pip3 install ansible

  execute_ansible:
    name: Execute Ansible Playbook
    runs-on: ubuntu-latest
    needs: setup_ec2
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Configure SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/hosts ansible/playbooks/install_haproxy.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: "False"
