name: Deploy WordPress to Private EC2 with SSM

on:
  push:
    branches:
      - main
    paths:
      - "platforms/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE }}
        aws-region: eu-west-1
        audience: sts.amazonaws.com

    - name: Deploy WordPress via SSM
      run: |
        aws ssm send-command \
          --instance-ids ${{ env.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Deploy WordPress Docker Compose" \
          --parameters '{"commands":["cd ~/app", 
            "echo WORDPRESS_DB_HOST=mysql:3306 >> .env", 
            "echo WORDPRESS_DB_NAME=wordpress >> .env", 
            "echo WORDPRESS_DB_USER=bn_wordpress >> .env", 
            "echo WORDPRESS_DB_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }} >> .env", 
            "echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env", 
            "echo MYSQL_DATABASE=wordpress >> .env", 
            "echo MYSQL_USER=bn_wordpress >> .env", 
            "echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env", 
            "docker compose -f apps/wordpress/docker-compose.yml up -d"]}' \
          --output text

    - name: Verify deployment
      run: |
        # Wait a bit for containers to start
        sleep 30
        
        aws ssm send-command \
          --instance-ids ${{ env.EC2_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Check Docker containers status" \
          --parameters '{
            "commands":[
              "cd ~/app",
              "echo \"Container Status:\"",
              "docker compose -f apps/wordpress/docker-compose.yml ps --format json",
              "echo \"Container Logs (last 10 lines):\"",
              "docker compose -f apps/wordpress/docker-compose.yml logs --tail=10",
              "# Check if containers are running",
              "if ! docker compose -f apps/wordpress/docker-compose.yml ps --format json | grep -q \"\\\"State\\\": \\\"running\\\"\"; then",
              "  echo \"Error: Not all containers are running\"",
              "  exit 1",
              "fi"
            ]
          }' \
          --output text

