name: Deploy WordPress to Private EC2 with SSM

on:
  push:
    branches:
      - main
    paths:
      - "platforms/**"
      - ".github/workflows/deploy-wordpress.yml"
      - "apps/docker-compose.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        role-to-assume: ${{ secrets.OIDC_ROLE }}
        aws-region: eu-west-1
        audience: sts.amazonaws.com

    - name: Configure SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.BASTION_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Copy Docker Compose files to EC2
      run: |
        scp -o StrictHostKeyChecking=no -r apps/wordpress/ ubuntu@${{ vars.BASTION_HOST }}:~/

    - name: SSH into Bastion Host and Deploy to Private EC2
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ vars.BASTION_HOST }}
        username: ${{ vars.BASTION_USER }} 
        key: ${{ secrets.BASTION_PRIVATE_KEY }}
        port: 22
        script: |
          scp -o StrictHostKeyChecking=no -i .ssh/wp_server_keypair_private_key.pem -r ~/wordpress ubuntu@${{ vars.WP_HOST }}:~/
          # SSH to the private EC2 instance from the bastion host
          ssh -o StrictHostKeyChecking=no -T -i .ssh/wp_server_keypair_private_key.pem ubuntu@${{ vars.WP_HOST }} << 'EOF'
            # Deploy Docker Compose files directly from the repo
            ls
            cd ~/wordpress
            echo WORDPRESS_DATABASE_HOST=mysql:3306 >> .env
            echo WORDPRESS_DATABASE_NAME=wordpress >> .env
            echo WORDPRESS_DATABASE_USER=bn_wordpress >> .env
            echo WORDPRESS_DATABASE_PASSWORD=${{ secrets.WORDPRESS_DB_PASSWORD }} >> .env
            echo MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} >> .env
            echo MYSQL_DATABASE=wordpress >> .env
            echo MYSQL_USER=bn_wordpress >> .env
            echo MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} >> .env
            ls
            docker compose down
            docker compose up -d
            docker ps
          EOF
