version: '3.8'

services:
  wordpress:
    image: bitnami/wordpress:latest
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
      - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME}
      - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
      - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - wordpress_data:/bitnami/wordpress
    depends_on:
      - mysql

  mysql:
    image: bitnami/mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/bitnami/mysql

volumes:
  wordpress_data:
    driver: local
  mysql_data:
    driver: local
